// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --local > types/database.ts
// For now, we'll define a basic type structure

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          preferred_currency: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          preferred_currency?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          preferred_currency?: string
          created_at?: string
          updated_at?: string
        }
      }
      bank_connections: {
        Row: {
          id: string
          user_id: string
          powens_connection_id: string
          bank_name: string
          bank_logo_url: string | null
          status: 'active' | 'error' | 'disconnected' | 'pending'
          last_sync_at: string | null
          error_message: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          powens_connection_id: string
          bank_name: string
          bank_logo_url?: string | null
          status: 'active' | 'error' | 'disconnected' | 'pending'
          last_sync_at?: string | null
          error_message?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          powens_connection_id?: string
          bank_name?: string
          bank_logo_url?: string | null
          status?: 'active' | 'error' | 'disconnected' | 'pending'
          last_sync_at?: string | null
          error_message?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      accounts: {
        Row: {
          id: string
          user_id: string
          connection_id: string | null
          powens_account_id: string | null
          name: string
          type: 'checking' | 'savings' | 'investment' | 'crypto' | 'real_estate' | 'loan' | 'credit_card' | 'other'
          institution_name: string | null
          balance: number
          currency: string
          is_manual: boolean
          is_included_in_networth: boolean
          display_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          connection_id?: string | null
          powens_account_id?: string | null
          name: string
          type: 'checking' | 'savings' | 'investment' | 'crypto' | 'real_estate' | 'loan' | 'credit_card' | 'other'
          institution_name?: string | null
          balance?: number
          currency?: string
          is_manual?: boolean
          is_included_in_networth?: boolean
          display_order?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          connection_id?: string | null
          powens_account_id?: string | null
          name?: string
          type?: 'checking' | 'savings' | 'investment' | 'crypto' | 'real_estate' | 'loan' | 'credit_card' | 'other'
          institution_name?: string | null
          balance?: number
          currency?: string
          is_manual?: boolean
          is_included_in_networth?: boolean
          display_order?: number
          created_at?: string
          updated_at?: string
        }
      }
      transactions: {
        Row: {
          id: string
          account_id: string
          powens_transaction_id: string | null
          date: string
          description: string
          amount: number
          currency: string
          category: string | null
          subcategory: string | null
          tags: string[] | null
          is_pending: boolean
          is_manual: boolean
          user_description: string | null
          user_category: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          account_id: string
          powens_transaction_id?: string | null
          date: string
          description: string
          amount: number
          currency?: string
          category?: string | null
          subcategory?: string | null
          tags?: string[] | null
          is_pending?: boolean
          is_manual?: boolean
          user_description?: string | null
          user_category?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          account_id?: string
          powens_transaction_id?: string | null
          date?: string
          description?: string
          amount?: number
          currency?: string
          category?: string | null
          subcategory?: string | null
          tags?: string[] | null
          is_pending?: boolean
          is_manual?: boolean
          user_description?: string | null
          user_category?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      balance_history: {
        Row: {
          id: string
          account_id: string
          balance: number
          currency: string
          recorded_at: string
          created_at: string
        }
        Insert: {
          id?: string
          account_id: string
          balance: number
          currency?: string
          recorded_at: string
          created_at?: string
        }
        Update: {
          id?: string
          account_id?: string
          balance?: number
          currency?: string
          recorded_at?: string
          created_at?: string
        }
      }
      sync_logs: {
        Row: {
          id: string
          user_id: string
          connection_id: string | null
          status: 'success' | 'error' | 'partial'
          accounts_synced: number
          transactions_synced: number
          error_message: string | null
          started_at: string
          completed_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          connection_id?: string | null
          status: 'success' | 'error' | 'partial'
          accounts_synced?: number
          transactions_synced?: number
          error_message?: string | null
          started_at: string
          completed_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          connection_id?: string | null
          status?: 'success' | 'error' | 'partial'
          accounts_synced?: number
          transactions_synced?: number
          error_message?: string | null
          started_at?: string
          completed_at?: string | null
          created_at?: string
        }
      }
      powens_webhooks: {
        Row: {
          id: string
          webhook_id: string
          event_type: string
          payload: Json
          processed: boolean
          processed_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          webhook_id: string
          event_type: string
          payload: Json
          processed?: boolean
          processed_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          webhook_id?: string
          event_type?: string
          payload?: Json
          processed?: boolean
          processed_at?: string | null
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      calculate_net_worth: {
        Args: {
          p_user_id: string
        }
        Returns: number
      }
      get_asset_allocation: {
        Args: {
          p_user_id: string
        }
        Returns: {
          account_type: string
          total_amount: number
          percentage: number
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
  }
}
